name: eat_fresh_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.1
  lottie: ^2.3.1
  flutter_screenutil: ^5.7.0

  get: ^4.6.5
  get_storage: ^2.1.1

  dio: ^5.1.1
  connectivity_plus: ^3.0.3

  intl: ^0.18.0
  crypto: ^3.0.2
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Black.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Bold.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Light.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Medium.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Thin.ttf