/// <<< Entire app all type of constant --------- >>>

class Constant {
  // App Config .....

  // Api Config .....
  static const String baseUrl = '';

  // Firebase Config .....

  // App Secrets .....
}
